### PR TITLE
Convert Demo app to SASS

### PR DESCRIPTION
**Pull request by JPEscobari**
This pull request includes class name changes to the structure of several components in the `DemoPage` directory.

The main changes involve converting CSS files to SCSS for better modularity and maintainability, and updating class names to follow a more consistent naming convention.

Summary:

- Removed (some) unused CSS styles.
- Updated import in .jsx components to use the new `.scss` file for styles.
- Modified class names to follow BEM naming convention.
- Utility Classes (such as `.bold`) moved to `index.css`.
- Moved selectors corresponding to `DemoFlashCardsGameModal.jsx` (like flaschard-btns, correct-btn) to `DemoFlashCardsGameModal.scss`
- Removed duplicated classes for "arrowBack" in `LeftSideBar.jsx`.
- Fixed a typo in Line 29 for `DemoPreviewTextModal.jsx` that was preventing the dark backdrop from being applied.

<sub><a href="https://huly.app/guest/knownative?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzQ0ZGRiMGQyZWY0Y2JjYzQ2OGVhM2EiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWJpZ2FpbGRhd3NvLWtub3duYXRpdmUtNjYzMjgxYjEtODdiZTE2ZDY5OS0yYTZiY2QifQ.-eHRMyTHmUtOIN-1Duo7Ig--bpjL5Cs8e1491DSIaQs">Huly&reg;: <b>GITHB-160</b></a></sub>

### CODE REVIEW

**Review by AbigailDawson — CHANGES_REQUESTED** [review]
JP, can you check that your branch is up to date with the latest from `develop`? I found some errors and pages that are not working on your branch that are working on the `develop` branch. I tried to merge `develop` into yours but for some reason (maybe because it's a fork?) it didn't resolve the errors. It might be easier to clone+branch off `develop` directly rather than through a fork.

Let me know if you're not able to resolve these by merging in the latest from `develop` (no new code should be needed, it's just a branching issue):

1. styling on welcome modal
Screenshot 2024-11-25 at 10 29 59 PM

2. blank study tab
Screenshot 2024-11-25 at 10 30 17 PM

3. blank translate tab
Screenshot 2024-11-25 at 10 30 38 PM

4. error messages in console related to getTokenizedText and fetchTranslation (should resolve when 2 & 3 are fixed)
Screenshot 2024-11-25 at 10 35 56 PM

**Comment by JPEscobari** [comment]
Thank you for all the detail Abigail.

I was able to update my `JP` branch by merging in the latest changes from develop.

Bumped into an issue where I was missing that CORS intallation, but then I was able to run the app.

The screenshots really did help a lot to verify the merge, but let me know if something else pops up.

**Review by JPEscobari — COMMENTED** [review]
**Fix for _Study_ and _Translate_ tabs not displaying any text.**

After further investigation, I found out there were class names in `DemoTextPage.jsx` that were affecting elements in the Study and Translate pages, preventing them from displaying.

Everything is working just fine now, and I believe ready to merge with @Seanna-Arnold 's work and the  `develop` branch.

**Review by JPEscobari — COMMENTED** [review]
### Fix for `DemoWelcomeModal.jsx` not displaying the difficulty selection boxes in full width.

This commit addresses the first issue @AbigailDawson brought up in her screenshots, were difficulty selection boxes in the Welcome Modal were not displaying in full width.

Here's a screenshot after applying this fix:

image

**Pull request merged**
